### PR TITLE
Solve N Problem and Test Repository

### PR DESCRIPTION
**Pull request by cancelei**
Here:
- We solved the N+1 problem when fetching
- We used Capybara to write integration tests for each view in our project.
- User index page:
I can see the username of all other users.
I can see the profile picture for each user.
I can see the number of posts each user has written.
When I click on a user, I am redirected to that user's show page.
- user show page:
I can see the user's profile picture.
I can see the user's username.
I can see the number of posts the user has written.
I can see the user's bio.
I can see the user's first 3 posts.
I can see a button that lets me view all of a user's posts.
When I click a user's post, it redirects me to that post's show page.
When I click to see all posts, it redirects me to the user's post's index page.
- User post index page:
I can see the user's profile picture.
I can see the user's username.
I can see the number of posts the user has written.
I can see a post's title.
I can see some of the post's body.
I can see the first comments on a post.
I can see how many comments a post has.
I can see how many likes a post has.
I can see a section for pagination if there are more posts than fit on the view.
When I click on a post, it redirects me to that post's show page.
- User post index page:
I can see the user's profile picture.
I can see the user's username.
I can see the number of posts the user has written.
I can see a post's title.
I can see some of the post's body.
I can see the first comments on a post.
I can see how many comments a post has.
I can see how many likes a post has.
I can see a section for pagination if there are more posts than fit on the view.
When I click on a post, it redirects me to that post's show page.
- here you can see the log before and after solving n+1 problem:
Screenshot 2023-10-19 103155
Screenshot 2023-10-19 103205

### CODE REVIEW

**Comment by cancelei** [comment]
Pair Programming work was done and approved for other 2 members in this PR>

https://github.com/cancelei/blog-in-rails/pull/8

**Comment by AbelG101** [comment]
# Hi @cancelei 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- As per the project requirements each Student must request reviews individually on their respective repository which means you're not meant to share the same PR. I can see that this review request is for student Glauber Bannwart so please make sure to work on their repo and submit a link accordingly.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by cancelei** [comment]
Pair Programming work was done and approved for other 2 members in this PR>

https://github.com/cancelei/blog-in-rails/pull/8

Glauber Bannwart is cancelei

**Comment by AbelG101** [comment]
Hello @cancelei my apologies for confusing your GitHub handle with your actual name previously but since [PR](https://github.com/cancelei/blog-in-rails/pull/8) has been approved multiple times and requested changes by another reviewer we're trying to investigate the issue so please wait patiently It'll be resolved soon, thank you!

**Review by AbelG101 — APPROVED** [review]
# Hi @cancelei 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Commented code is removed ✔
- Correct use of Git Flow ✔
- Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a good summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
